# Setting firefox for html and pdf

ext x?html?, has firefox, X, flag f = firefox -- "$@"
ext pdf, has firefox, X, flag f = firefox -- "$@"

# Setting nvim as text editor

mime ^text,  label editor = vim -- "$@"
mime ^text,  label pager  = vim -- "$@"

# Setting swayimg as image viewer

mime ^image, has swayimg, X, flag f = swayimg -- "$@"

# Setting mpv as audio/video player

mime ^audio|ogg$, X, has mpv = mpv -- "$@"
mime ^video, X, has mpv = mpv -- "$@"
